### ISSUE TITLE
Information on how the solution is interpolated in the fft module

### ISSUE THREAD

**Issue by NicoClinco** [flexi-framework/flexi#16]
Hello,
i open this issue just to ask an information:
I've seen in the script 'fft.f90' that in order to interpolate the DG solution to an equispaced grid there is the subroutine 'Interpolate_DG2FFT'. 
I have noted that the solution is interpolated inside each element to equispaced points first by changing the basis by 'ChangeBasis3D' and then locating the equispaced nodes from local-to-global equispaced nodes.
Now, i have a doubt: how the points located on each face shared by two elements are treated? I ask this, because, if i am not wrong, the solution should be discontinuos across each element, thus, i supposed that the values at each point shared by two elements must be an average, but i cannot see any average in the script. Maybe the final results is not so much affected by this trick and only the lowest wave numbers are affected?
Thanks in advance for the answer,
Nicola

**Comment by m-kurz** [comment]
Hi Nicola,
thanks for reaching out and sorry for the late response.

You are in principle correct, we interpolate the solution within each element to an equispaced basis where the nodes are displaced by `h` and use this to build a global equispaced basis with a step size `h` to perform FFT on.
However, we interpolate the nodes to the `VISU_INNER` instead of `VISU` nodes in FLEXI nomenclature.
The latter includes the faces of each element, i.e. we are equispaced in the interval [-1, 1], while the former one explicitly excludes the surface nodes and is displaced by half a step size `h/2`.
This means for `VISU_INNER` the nodes are equispaced in the interval [-1+h/2, +1-h/2].
If you the take the neighbors into account, you see that globally you again get a global basis with step size `h`.

This has two reasons:

1. The FFT basis should be build on *unique* nodes. As you mentioned, if we include nodes on the surface we have two nodes at the same position and thus we end up with `N` unique nodes instead of `N+1` ones, which would be expected.
2. We avoid the problems and discontinuities at the element faces and to devise some averaging operation there.

This approximation of course might be problematic if the discontinuities become large, i.e. if the simulation is underresolved.
However, this problem arises simply because computing an FFT across discontinuous data is somewhat ill-defined.
Excluding the faces seems like a similarly sensible approach as averaging while keeping the advantage of having unique nodes that are directly defined by `N` instead of having to take into account that we 'lose' a node on the edges.
In a DNS setting, these jumps should vanish, the solution should become quasi-continuous and it will not make any difference.

Hope that helps!
Marius

**Comment by m-kurz** [comment]
I will close the Issue for now. Feel free to re-open if you have further questions.
