### ISSUE TITLE
cmake-check for ctags is broken, INSTALL.md is not correct 

### ISSUE THREAD

**Issue by rotdrop** [flexi-framework/flexi#4]
Hi,
as system admin of the Maths dpt. at the university of stuttgart I was lately bothered by one of the collegues because flexi would not install.

First point: you just check for  the program-name "ctags" and then silently assumes that anything called "ctags" automatically is "exuberant-ctags" which of course need not be the case. Could you please either check your cmake-check or at least list exuberant-ctags in the requirements table and also note there that the package will fail to compile if another ctags flavour is installed? Kind thanks.

Second minor point: you list cmake-curses-gui as requirement. This is not nice because this potentially triggers other people (like me) to install a non-requirement only because someone else needs this flexi kind of thing. Could you please keep the table of requirements to the bare minimum? 

Thank you.

**Comment by tbole** [comment]
Fixes in e2ff08f833cb373ce6112d6a59adad7a0f90a643

We have silently assumed ctags always to be identical to ctags-exuberant, which is not the case. We now explicitly search and use the later. However ctags is not a requirement and it's only used if available.

You're right the cmake-curses-gui aka ccmake is optional. Though we strongly encourage people to use some sort of frontend to cmake and imo any halfway decent development environment should include one, since it strongly eases working with the various compile options. Flexi has been designed and is intended to be used primarily on HPC clusters, thus a shell-based tool like ccmake, distributed together with cmake, is the most natural option.
