### ISSUE TITLE
Does not compile with GCC 10

### ISSUE THREAD

**Issue by michaelkuhn** [flexi-framework/flexi#7]
Due to a change in GCC 10 (see https://gcc.gnu.org/gcc-10/changes.html#fortran), FLEXI needs the `-fallow-argument-mismatch` flag to be set to compile successfully.

**Comment by flexi-framework** [comment]
We just tried to recreate your issue with GCC 10. For GCC 10.2.1 and an experimental version of GCC 11 we couldn't see this problem. Are you using some kind of IDE? Specifically Visual Studio Code. In this case the built in IntelliSense precompiles part of the code. The resulting mods_*_vars.mod files can cause these kind of issues.

**Comment by michaelkuhn** [comment]
Thanks for your feedback. I am not using an IDE, just plain shell. I did the following:
```console
$ module load gcc
$ module load mpich
$ module load hdf5
$ module load cmake
$ module load zlib
$ module load openblas
$ git clone https://github.com/flexi-framework/flexi.git
$ cd flexi
$ mkdir build
$ cd build
$ cmake -DFLEXI_BUILD_HDF5=OFF ..
$ make
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: .../opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/gcc-10.2.0-3msojcki7ssxqdyhslmqoodd3pxmmral/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: .../opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/gcc-10.2.0-3msojcki7ssxqdyhslmqoodd3pxmmral/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 10.2.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
...
[ 11%] Building Fortran object CMakeFiles/libflexistaticF90.dir/src/equations/navierstokes/calcbodyforces.f90.o
.../flexi/src/equations/navierstokes/calcbodyforces.f90:96:18:

   92 |   CALL MPI_REDUCE(MPI_IN_PLACE,Box,6*nBCs,MPI_DOUBLE_PRECISION,MPI_SUM,0,MPI_COMM_FLEXI,iError)
      |                  2
......
   96 |   CALL MPI_REDUCE(Box         ,0  ,6*nBCs,MPI_DOUBLE_PRECISION,MPI_SUM,0,MPI_COMM_FLEXI,iError)
      |                  1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
```

**Comment by flexi-framework** [comment]
Thank you for providing us with the information. We were able to recreate exactly the same problem. However we believe that this is more of an MPICH issue than a problem with our code. 

In its current version MPICH doesn't seamlessly compile with gfortran-10. See [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91731). Therefore you have to enable the `-fallow-argument-mismatch` in order to avoid problems during the building process of MPICH. Doing so and linking the MPICH libraries to FLEXI yields the problem you described above.

Since this issue only occurs with MPICH in combination with gfortran-10 we believe that it is not rational to make large scale modifications in our code, since this issue will most likely be fixed in a future MPICH release.

For now we can recommend you two options to get FLEXI to work.

1. MPICH with GNU 9 compilers
2. OpenMPI instead of MPICH

**Comment by michaelkuhn** [comment]
I gave it a try with OpenMPI and that seems to work, thanks!

FYI: flexi will probably also be available via Spack soon: https://github.com/spack/spack/pull/20313
